#!/usr/bin/env php
<?php

$host = 'localhost';
$port = '3333';
$publicDir = __DIR__ . '/public';

echo "🚀 Starting development server at http://$host:$port\n";
echo "📂 Document root: $publicDir\n";
echo "Press Ctrl+C to stop the server\n\n";

//passthru("php -S $host:$port -t $publicDir");
passthru("php -S $host:$port -t $publicDir $publicDir/router.php");

